version: "3.7"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: hvpulok/lockessential:latest
    deploy:
      # scale the instances
      replicas: 3
      restart_policy:
        condition: on-failure
    ports:
      - "8080:80"
    environment:
      NODE_ENV:
      DOMAIN:
      SERVER_KEY:
      SESSION_SECRET:
      MONGOHQ_URL:
      FACEBOOK_ID:
      FACEBOOK_SECRET:
      GOOGLE_ID:
      GOOGLE_SECRET:
      MAILER_FROM:
      MAILER_SERVICE_PROVIDER:
      MAILER_EMAIL_ID:
      MAILER_PASSWORD:
